### ISSUE TITLE
RecyclerView returns already deleted item on back pressed and activity resumed

### ISSUE THREAD

**Issue by mayokunthefirst** [mayokunthefirst/Shopping-List#1]
The [ListActivity.class](https://github.com/mayokunthefirst/Shopping-List/blob/master/app/src/main/java/com/example/myapplication/Activities/ListActivity.java) displays a list of all available items in the [SQLite DB](https://github.com/mayokunthefirst/Shopping-List/blob/master/app/src/main/java/Data/DataBaseHandler.java) with two options to delete or edit each item. Both the delete and edit buttons work fine for each item, BUT if the user presses the back button exiting the application and then resumes the application again, the items that were deleted come up again!

**Comment by djubreel** [comment]
Created a PR to fix this.

**Comment by mayokunthefirst** [comment]
Thanks a lot @djubreel 😎
